-- Kakeibo prototype schema
-- Demo rows only are accessible to the unauthenticated prototype.
-- Real household data must use authenticated RLS before being inserted.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.merchant_rules (
  id bigint generated by default as identity primary key,
  merchant_name text not null,
  category_id bigint references public.categories(id) on delete set null,
  scope text not null default 'shared' check (scope in ('shared','mine','partner')),
  mode text not null default 'auto' check (mode in ('auto','confirm','manual')),
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null,
  merchant_name text not null,
  merchant_raw text,
  amount integer not null check (amount >= 0),
  category_id bigint references public.categories(id) on delete set null,
  scope text check (scope in ('shared','mine','partner')),
  payer text check (payer in ('me','partner')),
  status text not null default 'unclassified' check (status in ('unclassified','confirmed','refunded')),
  source text not null default 'manual' check (source in ('manual','epos_email','csv')),
  source_message_id text unique,
  memo text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  loan_date date not null,
  description text not null,
  amount integer not null check (amount > 0),
  lender text not null check (lender in ('me','partner')),
  borrower text not null check (borrower in ('me','partner')),
  status text not null default 'open' check (status in ('open','settled')),
  memo text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  check (lender <> borrower)
);

create table if not exists public.repayment_plans (
  id bigint generated by default as identity primary key,
  title text not null,
  original_amount integer not null check (original_amount >= 0),
  remaining_amount integer not null check (remaining_amount >= 0),
  monthly_amount integer not null default 0 check (monthly_amount >= 0),
  lender text not null check (lender in ('me','partner')),
  borrower text not null check (borrower in ('me','partner')),
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  check (lender <> borrower),
  check (remaining_amount <= original_amount)
);

create table if not exists public.repayments (
  id bigint generated by default as identity primary key,
  repayment_plan_id bigint not null references public.repayment_plans(id) on delete cascade,
  repayment_date date not null,
  amount integer not null check (amount > 0),
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.merchant_rules enable row level security;
alter table public.transactions enable row level security;
alter table public.loans enable row level security;
alter table public.repayment_plans enable row level security;
alter table public.repayments enable row level security;

grant select on public.categories to anon;
grant select, insert on public.merchant_rules to anon;
grant select, update on public.transactions to anon;
grant select on public.loans to anon;
grant select, update on public.repayment_plans to anon;
grant select on public.repayments to anon;
grant usage, select on all sequences in schema public to anon;

create policy "demo categories select" on public.categories
  for select to anon using (is_demo = true);
create policy "demo merchant rules select" on public.merchant_rules
  for select to anon using (is_demo = true);
create policy "demo merchant rules insert" on public.merchant_rules
  for insert to anon with check (is_demo = true);
create policy "demo transactions select" on public.transactions
  for select to anon using (is_demo = true);
create policy "demo transactions update" on public.transactions
  for update to anon using (is_demo = true) with check (is_demo = true);
create policy "demo loans select" on public.loans
  for select to anon using (is_demo = true);
create policy "demo repayment plans select" on public.repayment_plans
  for select to anon using (is_demo = true);
create policy "demo repayment plans update" on public.repayment_plans
  for update to anon using (is_demo = true) with check (is_demo = true);
create policy "demo repayments select" on public.repayments
  for select to anon using (is_demo = true);


-- Foreign-key indexes
create index if not exists merchant_rules_category_id_idx on public.merchant_rules(category_id);
create index if not exists transactions_category_id_idx on public.transactions(category_id);
create index if not exists repayments_repayment_plan_id_idx on public.repayments(repayment_plan_id);
