-- Kakeibo initial schema
-- Supabase SQL Editor / migration で実行する想定

create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.merchant_rules (
  id bigint generated by default as identity primary key,
  merchant_name text not null,
  category_id bigint references public.categories(id) on delete set null,
  scope text not null default 'shared' check (scope in ('shared','mine','partner')),
  mode text not null default 'auto' check (mode in ('auto','confirm','manual')),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null,
  merchant_name text not null,
  merchant_raw text,
  amount integer not null check (amount >= 0),
  category_id bigint references public.categories(id) on delete set null,
  scope text check (scope in ('shared','mine','partner')),
  payer text check (payer in ('me','partner')),
  status text not null default 'unclassified' check (status in ('unclassified','confirmed','refunded')),
  source text not null default 'manual' check (source in ('manual','epos_email','csv')),
  source_message_id text unique,
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  loan_date date not null,
  description text not null,
  amount integer not null check (amount > 0),
  lender text not null check (lender in ('me','partner')),
  borrower text not null check (borrower in ('me','partner')),
  status text not null default 'open' check (status in ('open','settled')),
  memo text,
  created_at timestamptz not null default now(),
  check (lender <> borrower)
);

create table if not exists public.repayment_plans (
  id bigint generated by default as identity primary key,
  title text not null,
  original_amount integer not null check (original_amount >= 0),
  remaining_amount integer not null check (remaining_amount >= 0),
  monthly_amount integer not null default 0 check (monthly_amount >= 0),
  lender text not null check (lender in ('me','partner')),
  borrower text not null check (borrower in ('me','partner')),
  created_at timestamptz not null default now(),
  check (lender <> borrower),
  check (remaining_amount <= original_amount)
);

create table if not exists public.repayments (
  id bigint generated by default as identity primary key,
  repayment_plan_id bigint not null references public.repayment_plans(id) on delete cascade,
  repayment_date date not null,
  amount integer not null check (amount > 0),
  created_at timestamptz not null default now()
);

create or replace view public.transactions_view as
select
  t.id,
  t.transaction_date as date,
  t.merchant_name,
  t.merchant_raw,
  t.amount,
  c.name as category_name,
  c.id as category_id,
  t.scope,
  t.payer,
  t.status,
  t.source,
  t.memo,
  t.created_at
from public.transactions t
left join public.categories c on c.id = t.category_id;

create or replace view public.merchant_rules_view as
select
  r.id,
  r.merchant_name,
  c.name as category_name,
  c.id as category_id,
  r.scope,
  r.mode,
  r.created_at
from public.merchant_rules r
left join public.categories c on c.id = r.category_id;

-- 初期段階では公開サイトから匿名ユーザーが読むための仮設定。
-- 本番ではAuth導入時に authenticated ユーザー限定へ変更する。
alter table public.categories enable row level security;
alter table public.merchant_rules enable row level security;
alter table public.transactions enable row level security;
alter table public.loans enable row level security;
alter table public.repayment_plans enable row level security;
alter table public.repayments enable row level security;

drop policy if exists "prototype read categories" on public.categories;
create policy "prototype read categories" on public.categories for select using (true);

drop policy if exists "prototype read merchant rules" on public.merchant_rules;
create policy "prototype read merchant rules" on public.merchant_rules for select using (true);

drop policy if exists "prototype read transactions" on public.transactions;
create policy "prototype read transactions" on public.transactions for select using (true);

drop policy if exists "prototype read loans" on public.loans;
create policy "prototype read loans" on public.loans for select using (true);

drop policy if exists "prototype read repayment plans" on public.repayment_plans;
create policy "prototype read repayment plans" on public.repayment_plans for select using (true);

-- 仮プロトタイプで分類修正・返済額変更を試すための更新許可。
-- 本番化前に必ずAuthベースへ置き換える。
drop policy if exists "prototype update transactions" on public.transactions;
create policy "prototype update transactions" on public.transactions for update using (true) with check (true);

drop policy if exists "prototype insert merchant rules" on public.merchant_rules;
create policy "prototype insert merchant rules" on public.merchant_rules for insert with check (true);

drop policy if exists "prototype update repayment plans" on public.repayment_plans;
create policy "prototype update repayment plans" on public.repayment_plans for update using (true) with check (true);