create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  owner text not null check (owner in ('me','partner')),
  provider text not null,
  name text not null,
  last4 text,
  created_at timestamptz not null default now(),
  constraint cards_last4_check check (last4 is null or last4 ~ '^[0-9]{4}$')
);

create unique index if not exists cards_identity_uidx
  on public.cards (owner, provider, lower(name), coalesce(last4, ''));

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  uploader_user_id uuid default auth.uid(),
  uploader_email text default (auth.jwt() ->> 'email'),
  uploaded_at timestamptz not null default now(),
  target_month date not null,
  card_id bigint not null references public.cards(id) on delete restrict,
  file_name text not null,
  source_format text not null check (source_format in ('csv','pdf')),
  read_count integer not null default 0 check (read_count >= 0),
  imported_count integer not null default 0 check (imported_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  error_count integer not null default 0 check (error_count >= 0),
  total_amount integer not null default 0,
  created_at timestamptz not null default now(),
  constraint import_batches_target_month_first_day_check
    check (target_month = date_trunc('month', target_month)::date)
);

alter table public.transactions
  add column if not exists card_id bigint references public.cards(id) on delete set null,
  add column if not exists import_batch_id bigint references public.import_batches(id) on delete set null;

create index if not exists transactions_card_id_idx on public.transactions(card_id);
create index if not exists transactions_import_batch_id_idx on public.transactions(import_batch_id);
create index if not exists import_batches_card_id_idx on public.import_batches(card_id);
create index if not exists import_batches_target_month_idx on public.import_batches(target_month);
create index if not exists import_batches_uploaded_at_idx on public.import_batches(uploaded_at desc);

alter table public.cards enable row level security;
alter table public.import_batches enable row level security;

revoke all on table public.cards from anon, authenticated;
revoke all on table public.import_batches from anon, authenticated;

grant select, insert on table public.cards to authenticated;
grant select, insert, delete on table public.import_batches to authenticated;
grant usage, select on sequence public.cards_id_seq, public.import_batches_id_seq to authenticated;

drop policy if exists "authorized user cards select" on public.cards;
create policy "authorized user cards select"
  on public.cards for select to authenticated
  using ((select private.kakeibo_is_allowed()));

drop policy if exists "authorized user cards insert" on public.cards;
create policy "authorized user cards insert"
  on public.cards for insert to authenticated
  with check ((select private.kakeibo_is_allowed()));

drop policy if exists "authorized user import batches select" on public.import_batches;
create policy "authorized user import batches select"
  on public.import_batches for select to authenticated
  using ((select private.kakeibo_is_allowed()));

drop policy if exists "authorized user import batches insert" on public.import_batches;
create policy "authorized user import batches insert"
  on public.import_batches for insert to authenticated
  with check ((select private.kakeibo_is_allowed()));

drop policy if exists "authorized user import batches delete" on public.import_batches;
create policy "authorized user import batches delete"
  on public.import_batches for delete to authenticated
  using ((select private.kakeibo_is_allowed()));
